### ISSUE TITLE
windows: clicking & dragging on a node doesn't move it around

### ISSUE THREAD

**Issue by akavel** [enso-org/ide#1147] opened 2021-01-26 23:38 UTC
### General Summary

![issue01 01](https://user-images.githubusercontent.com/273837/105920423-a6a17900-6037-11eb-9179-fdbcf9d975fc.gif)

### Steps to Reproduce

1. Open Enso IDE on Windows 10
2. Try moving a node around
     - mouse selection rectangle opens instead
3. Click and drag a point ~1cm above a node
    - the node gets moved around

### Expected Result

clicking and dragging a node should move it around

### Actual Result

I must click and drag ~1cm above a node to move the node around

### Enso Version

v2.0.0-alpha.1

### Additional notes
Maybe related to HiDPI or scaling? (I have scaling set to 225% in Windows Settings/Control Panel)

**Comment by farmaazon** [comment] 2021-01-27 11:59
@akavel Do you have only the dragging nodes affected by this "offset", or any interaction with GUI (like making connections, editing nodes etc.)? If everything is affected, it's likely duplicate of https://github.com/enso-org/ide/issues/1064

**Comment by akavel** [comment] 2021-01-27 12:33
It's kinda not practically usable with this, so hard for me to check making connections. FWIW, to edit a node I have to ctrl-click "1cm above" a node too.

Please note that I just tried changing Windows scaling settings down to 100% (i.e. no scaling) and it made the problem disappear. However I can't work like this because that's on a laptop and it makes everything microscopic and unusable (I was barely able to do the test with my nose in the screen and heavy squinting). So I'd suggesting to try using a Windows machine with scaling enabled in OS settings as a reproducer.

**Comment by akavel** [comment] 2021-01-27 19:24
@wdanilo suggested on Discord that a screen capture with ctrl-alt-shift-1 could be useful, so attaching one.

![issue01 02](https://user-images.githubusercontent.com/273837/106042191-ff771d00-60dc-11eb-8e15-599fb04e90d2.gif)

@MichaelMauderer noted that they can reproduce with 225% scaling, though that with 200% it works OK. I checked just now and indeed, 200% seems OK. I think this can be a workaround for me for the time being, 200% is a degraded experience but acceptable.

**Comment by wdanilo** [comment] 2021-01-27 20:09
@akavel this is strange. Your debug giff shows that actually we should read the correct values there (we just read pixel value from under the cursor). Could you also check if `ctrl-alt-shift-2` and `ctrl-alt-shift-3` look correct as well? I mean, the shapes are placed in the same positions when switching between them?

@MichaelMauderer could you check please what `window.devicePixelRatio` gives you for the following Windows zoom levels in Chrome: 100%, 125%, 150%, 200%, and 225%?

**Comment by akavel** [comment] 2021-01-27 20:27
@wdanilo `...-2` and `...-3` show the shapes in the same places. In fact `...-2` and `...-3` look completely identical to me. One thing I realized now, is that interestingly, `tab` seems to create a new node in a roughly correct place. Let me prepare another gif...

![issue01 03](https://user-images.githubusercontent.com/273837/106049383-57665180-60e6-11eb-92ca-e334c9a79571.gif)

**Comment by akavel** [comment] 2021-01-27 20:34
one more, to make it clear I'm indeed in 225%, not in the "working" 200% accidentally - and also to show a bit of how connections behave, guess that might be worth something to you too:

![issue01 04](https://user-images.githubusercontent.com/273837/106050317-613c8480-60e7-11eb-9a7f-72588009fef1.gif)

**Comment by akavel** [comment] 2021-01-27 20:38
Clicking in the code panel would appear to work well:

![issue01 05](https://user-images.githubusercontent.com/273837/106050840-ee7fd900-60e7-11eb-9b18-17047f019ab2.gif)

**Comment by wdanilo** [comment] 2021-01-27 22:13
@akavel This all makes sense. The connections, code-panel cursor, mouse cursor are using just cursor position which seems to be correct. Clicking on nodes, hovewer, samples our generated texture in mouse position and reads ID values from it. There has to be some problem - either with the texture or with the sampling logic, so all the above results seem very valid in such scenario! Thank you for tracking it down so deeply! Now it would be much simpler to search for it in the right place ❤️

**Comment by hughrawlinson** [comment] 2021-03-02 16:13
I'm getting this issue too - for my monitor, Windows defaults to 150% scaling.

**Comment by farmaazon** [comment] 2021-04-15 13:07
The issue with cursor offest on scaling not being a multiple of 100% is fixed: https://github.com/enso-org/ide/issues/1064 It should solve this issue as well. If you still have this problem on [our newest release](https://github.com/enso-org/ide/releases), please comment here and the issue will be reopened.

**Closed by farmaazon** 2021-04-15 13:07 UTC
Labels: Category: GUI, Difficulty: Hard, Priority: High, Type: Bug
