### ISSUE TITLE
Breadcrumbs Panel

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/ide#592] opened 2020-06-23 00:42 UTC
From the epic:

> The current execution context is displayed as a bread crumbs panel on top of the Graph Editor.
The first crumb is a entry point definition name, and the next are names of called definition. When
user click on the crumb the frames represented by crumbs after the clicked one are removed. The
crumbs of removed frames are grayed out, and then the user can click on them to restore all frames
up to clicked one.

Moreover, the first breadcrumb is the project name view, where:
1. Double clicking on it should enable project name editing.
2. Clicking on the background should accept the input and
3. Pressing enter should also accept the input.

This task covers creating the view component and exposing its relevant FRP endpoints for the Graph Editor integration.

**Comment by wdanilo** [comment] 2020-07-10 21:24
## Design

1. The current project name component should become a breadcrumbs component. The project name should be displayed as the first crumb on the breadcrumbs list.
2. I'm not sure whether breadcrumbs should be centered or not - we need to have both options and investigate them visually.
3. Each breadcrumb is an icon and a text. In case an icon is not provided, a default should be used. As part of this task, please implement the default icon using our shape system. Please be sure the implemented icon is pixel-perfect for the size of 16x16 px.
   ![image](https://user-images.githubusercontent.com/1623053/87203373-c32bcd00-c302-11ea-9cf4-e1bac45adf54.png)
4. Breadcrumbs should be separated by ">" symbol drawn in our shape system. The spacing between breadcrumbs, their icons and separators should be as seen below (it should automatically change in relation to text size change):
   ![image](https://user-images.githubusercontent.com/1623053/87203583-38979d80-c303-11ea-9a9d-b83fd3c5c2d5.png)
5. Inactive breadcrumbs should be dimmed out, as seen above.
6. When going back in history, the old breadcrumbs should be dimmed out, not deleted. So, having `A -> B -> C -> D`, where `D` is active, after clicking `B`, `C` and `D` should still be visible but dimmed out. There should be separate parameter setting the dimmed opacity of the inactive breadcrumbs on the left and on the right - we will adjust it after the logic is implemented.
7. New breadcrumbs should roll in (see animation below), old breadcrumbs should fade out. For example, in the scenario from point 6, after entering node X, the `X` breadcrumb should roll-in, while breadcrumbs `C -> D` should fade out. Please note that `X` should roll in before `C -> D` so for a moment we will see `A -> B -> X C -> D`, while the part `C -> D` will be fading out:
   ![bc](https://user-images.githubusercontent.com/1623053/87203861-c6738880-c303-11ea-8cdc-f2f5f4677053.gif)
8. In case of too many breadcrumbs (which should depend on scene width), several breadcrubs on the left should get collapsed to icon-only view, like this (however, lets make it simple - lets just fade out the text instead of moving it left):
   ![bc2](https://user-images.githubusercontent.com/1623053/87204038-28cc8900-c304-11ea-872f-5dcf209fd886.gif)
9. All things that are changing should be animated using our primary animation engine (not tweens, as tweens do not support breaking animation in the middle and changing its direction smoothly).
10. Double clicking on the first breadcrumb (project name) should allow renaming project as described in the renaming project task.
11. The speed of animations, the opacity etc should be just "good looking for you" - we will adjust them after the task logic will be done.

## Technical detail

There is one interesting thing happening here. As each breadcrumb will require custom animations, each breadcrumb should contain a separate `frp::Network`. This design is a special one - we do not use it anywhere but in new text implementation (for each cursor), although its not yet rolled into master yet.

**Comment by farmaazon** [comment] 2020-07-13 10:31
@wdanilo During planning our work for Community Release we assumed that the crumbs panel will be initially quite simple (with text only, the separators as a text characters, no collapsing). The problem is, that the design you described here make this task greatly underestimated, and I'm sure we won't make the agreed deadlines for epics.

I propose to return to the initial plan: to make just displayed crumbs as a one-line text panel, without icons, without pretty animations and without collapsing. And move the brilliant description to the new task, scheduled for later.

**Comment by wdanilo** [comment] 2020-07-15 07:36
@farmaazon I do not agree with a few points you made:

1. Animations need to be included in every part of the IDE we do and should be considered a part of a design for every task. Even if the task description is not mentioning animations explicitly, they should be there to keep the consistency of GUI elements. Making an animation is just writing 1 line `something = Animator::<f32>::new()` and you can now use it as FRP event. @notdanilo was using animations earlier and he told yesterday that there is almost no difference between implementing GUI elements with and without animations.

2. This is the problem with describing and chatting about tasks during planning. Tasks should be described up-front, with proper discussions, and then should be estimated. Icons should be there. Moreover, I do not understand what is the problem with icon implementation as it probably will take time similar to you + me writing these comments. I described above, that icons have to be just our shapes placed on left from the text, which is like a drawing the icon (triangle + circle - circle = max 15 mins), single call to `add_child`, and keeping the icon shape in the struct.

3. Regarding collapsing, lets split it to another task. I still don't see this as something not doable given the fact this task is 5 days long. Again, this is the problem with planning where we are trying to describe tasks ad-hoc, rather than earlier with proper discussions.

Moreover, if this task was meant to only be "text with separators", why it was estimated for 5 days? Danilo implemented its 1st version already in 1 day.

**Comment by farmaazon** [comment] 2020-07-15 09:44
Dear @wdanilo 

> Animations need to be included in every part of the IDE we do and should be considered a part of a design for every task.

So how many other such "implicit requirements" are there? I think you should then create a doc with all of these.

> This is the problem with describing and chatting about tasks during planning. Tasks should be described up-front, with proper discussions.

If you mean our Backlog Refinements, then I disagree - such scopes should be discussed a way before, when defining what features are required for release.

And we did that. We discussed about this matter when we planned the community release: and there we settled, that "let's it be a simplest breadcrumbs panel, even with single line of text with `>`, to meet our timelines". And this is what I put in the description and what I repeated during Backlog refinement. And the BR alone are not a place for discussing scopes.

>  I still don't see this as something not doable given the fact this task is 5 days long.

I think this is a misconception regarding estimates. The estimate doesn't mean "how much time we have for this task" but "how much time I believe it takes". If it seems to be take less - then great, but let's just take a next task, which in turn may take longer than the initial estimate.

> I described above, that icons have to be just our shapes placed on left from the text, which is like a drawing the icon (triangle + circle - circle = max 15 mins)

\+ placing them properly + testing them + appriopriate mouse events. No, I don't believe this is 15 min, especially for someone who is not as proficient in shapes as you.

And my concerns are not about icons only, but all those goodies - they all sum up to a bit of task IMO.

**Comment by wdanilo** [comment] 2020-07-16 16:01
> So how many other such "implicit requirements" are there? I think you should then create a doc with all of these.

Yeah, let's have a chat about it. I would love to first chat with you tomorrow about it and discuss it before making the doc. But you are right, lets formalize it.

> + placing them properly + testing them + appropriate mouse events. No, I don't believe this is 15 min, especially for someone who is not as proficient in shapes as you.

There are no mouse events in icons - just placing them. Danilo was creating shapes earlier - should be doable here in 15 mins - we can measure it to check if I'm right ;)


Regarding everything else, you are totally right and after thinking more about it, I agree completely. Let's have a call tomorrow about "implicit assumptions for every IDE part" - for me this comes down to animations + styles + shortcuts.

**Comment by notdanilo** [comment] 2020-07-24 18:54
Checklist with some questions:

1. ~~The current project name component should become a breadcrumbs component. The project name should be displayed as the first crumb on the breadcrumbs list.~~
2. I'm not sure whether breadcrumbs should be centered or not - we need to have both options and investigate them visually.
2.1 You mean the whole panel on the individual breadcrumbs? I think it makes more sense to keep it on the left if we want to make the breadcrumbs collapsible.
3. ~~Each breadcrumb is an icon and a text. In case an icon is not provided, a default should be used. As part of this task, please implement the default icon using our shape system. Please be sure the implemented icon is pixel-perfect for the size of 16x16 px.~~
4. ~~Breadcrumbs should be separated by ">" symbol drawn in our shape system. The spacing between breadcrumbs, their icons and separators should be as seen below (it should automatically change in relation to text size change):~~
5. ~~Inactive breadcrumbs should be dimmed out, as seen above.~~
6. ~~When going back in history, the old breadcrumbs should be dimmed out, not deleted. So, having `A -> B -> C -> D`, where `D` is active, after clicking `B`, `C` and `D` should still be visible but dimmed out. There should be separate parameter setting the dimmed opacity of the inactive breadcrumbs on the left and on the right - we will adjust it after the logic is implemented.~~
7. New breadcrumbs should roll in (see animation below), old breadcrumbs should fade out. For example, in the scenario from point 6, after entering node X, the `X` breadcrumb should roll-in, while breadcrumbs `C -> D` should fade out. Please note that `X` should roll in before `C -> D` so for a moment we will see `A -> B -> X C -> D`, while the part `C -> D` will be fading out:
8. In case of too many breadcrumbs (which should depend on scene width), several breadcrubs on the left should get collapsed to icon-only view, like this (however, lets make it simple - lets just fade out the text instead of moving it left):
9. ~~All things that are changing should be animated using our primary animation engine (not tweens, as tweens do not support breaking animation in the middle and changing its direction smoothly).~~
10. Double clicking on the first breadcrumb (project name) should allow renaming project as described in the renaming project task.
10.1. I can't avoid the first click of `TextField`, so it doesn't make sense to implement this double clicking operation atm.
11. ~~The speed of animations, the opacity etc should be just "good looking for you" - we will adjust them after the task logic will be done.~~

**Closed** 2020-08-19 22:24 UTC
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Hard, Priority: High, Type: Enhancement
