### ISSUE TITLE
Searcher is missing hints for numbers

### ISSUE THREAD

**Issue by wdanilo** [enso-org/ide#1241] opened 2021-02-24 10:46 UTC
The only hint I get is `up_to`:
![image](https://user-images.githubusercontent.com/1623053/108989436-e048bc80-7695-11eb-814a-9f55054e0253.png)

**Comment by farmaazon** [comment] 2021-02-24 11:32
Duplicate of https://github.com/enso-org/enso/issues/1445

**Closed by farmaazon** 2021-02-24 11:32 UTC
Labels: Type: Bug
