### ISSUE TITLE
Cannot select any nodes via the mouse

### ISSUE THREAD

**Issue by iconmaster5326** [enso-org/ide#1153] opened 2021-01-27 12:50 UTC
### General Summary
Left-clicking on any element in the GUI seems to do nothing. I cannot select nodes.

### Steps to Reproduce
1. Open Enso.
2. Attempt to left-click on the default "hello world" node.

### Expected Result
The node becomes selected.

### Actual Result
Nothing occurs.

### Enso Version
[v2.0.0-alpha.1](https://github.com/enso-org/ide/releases/tag/v2.0.0-alpha.1).

Also note that I am on Windows, version 10.0.19041.

**Comment by wdanilo** [comment] 2021-01-27 23:10
@iconmaster5326 can you try clicking above nodes, with like 1cm offset? We have another bug where on some systems the mouse position is shifted than what you see visually. Also, what system are you using and what is your system screen scaling?

**Comment by wdanilo** [comment] 2021-01-27 23:12
Possibly duplicate of: https://github.com/enso-org/ide/issues/1147

**Comment by iconmaster5326** [comment] 2021-01-28 01:50
I can confirm that clicking a bit above the node does the trick. It sounds like it is indeed a duplicate of enso-org/enso#2693.

**Closed** 2021-03-06 13:48 UTC
Labels: Category: GUI, Priority: High, Type: Bug
