### ISSUE TITLE
Fix ugly fonts on visualizations

### ISSUE THREAD

**Issue by wdanilo** [enso-org/ide#885] opened 2020-10-27 09:38 UTC

**Comment by sylwiabr** [comment] 2020-11-16 10:20
duplicate of https://app.zenhub.com/workspaces/enso-ide-5e99c2847b8a3027b334f1b9/issues/enso-org/ide/933

<blockquote><img src="No image" width="48" align="right"><div><img src="/dist/favicon/favicon-16x16.png" height="14"> ZenHub</div><div><strong><a href="https://zenhub.com">ZenHub</a></strong></div><div>Project Management and Software Development with GitHub | ZenHub</div></blockquote>

**Closed by sylwiabr** 2020-11-16 10:20 UTC
