### ISSUE TITLE
IDE Requests Permissions to Accept Incoming Network Connections

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/ide#741] opened 2020-08-20 10:00 UTC
### General Summary
Whenever the IDE .app is started on MacOS it requests permissions to accept incoming network connections. This doesn't seem to be needed as clicking "Deny" doesn't impact functionality. However, the chosen option should persist, and not be requested every time the application starts.

<img width="423" alt="Do you want the application Enso" src="https://user-images.githubusercontent.com/5780639/90756323-1adf3000-e2d4-11ea-85db-1fda56d0644c.png">

### Steps to Reproduce
1. Start Enso Studio

### Expected Result
I'm asked once, and the setting is persisted, or not asked at all.

### Actual Result
I'm asked every single time.

### Enso Version
```
5a4ba838f86d121ba6dd2980829a9bca32e3d56a
```

**Comment by BinarySoftware** [comment] 2020-12-04 16:31
Can't reproduce, for me when i clicked "always" once a loong time ago, it never shows up anymore. One thing - make sure that the IDE compilation has finished - by that i mean that the .app is signed and notarized. When i tried to open IDE before it has finished signing, it did show the popup, but now, opening the latest ide from main again and again, i don't see this popup. @sylwiabr can we close this issue?

**Comment by sylwiabr** [comment] 2020-12-04 21:12
yep, I didn't have this issue either

**Closed by sylwiabr** 2020-12-04 21:12 UTC
Labels: Category: Controllers, Difficulty: Intermediate, Priority: High, Type: Bug
