### ISSUE TITLE
Keyboard shortcuts for closing/quitting on MacOS don't work in Enso Studio

### ISSUE THREAD

**Issue by BinarySoftware** [enso-org/ide#258] opened 2020-03-12 18:01 UTC
### General Summary
Enso Studio should quit on macOS after clicking `command-Q` and should close the window after clicking `command-W`

### Steps to Reproduce
`command-W`
`command-Q`

### Expected Result
Window/Application should close

### Actual Result
Nothing happens

**Comment by wdanilo** [comment] 2020-03-16 05:55
This should be configurable from within application, so it has to be defined in our kb manager, then it should be send to the window via some channel (rpc-like) and then handled on the app side. It should be done, but not now.

**Comment by sylwiabr** [comment] 2020-12-11 16:20
duplicate of https://app.zenhub.com/workspaces/enso-ide-5e99c2847b8a3027b334f1b9/issues/enso-org/ide/769

<blockquote><img src="No image" width="48" align="right"><div><img src="/dist/favicon/favicon-16x16.png" height="14"> ZenHub</div><div><strong><a href="https://zenhub.com">ZenHub</a></strong></div><div>Project Management and Software Development with GitHub | ZenHub</div></blockquote>

**Closed by sylwiabr** 2020-12-11 16:20 UTC
Labels: Priority: Low, Type: Bug
