### ISSUE TITLE
Enso Studio edges and corners looks different then edges of the rest MacOS applications

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/ide#253] opened 2020-03-10 12:04 UTC
### General Summary

The MacOS applications have characteristic way of rounding corners. Our IDE looks different and it gives the feeling that it is inconsistent with the rest of the system. 
### Steps to Reproduce

Open Enso Studio on MacOS
### Expected Result

like for ie. discord:
<img width="121" alt="Zrzut ekranu 2020-03-10 o 12 53 47" src="https://user-images.githubusercontent.com/12892578/76310704-9a9db300-62cf-11ea-8a0a-a824f8667e40.png">

### Actual Result

<img width="120" alt="Zrzut ekranu 2020-03-10 o 12 52 30" src="https://user-images.githubusercontent.com/12892578/76310716-9f626700-62cf-11ea-97da-0721c44d0a23.png">

**Comment by wdanilo** [comment] 2020-03-16 06:06
I cannot reproduce it, but I have a feeling what it can be caused by on your side. Please check the build today evening and confirm if it's still there (the build will have window drag disabled)

**Comment by sylwiabr** [comment] 2020-03-17 09:35
Still the same. It is a fresh clean installation of Catalina so it should work properly.![Zrzut ekranu 2020-03-17 o 10.34.53.png](https://images.zenhubusercontent.com/5953b61961b4ca3b0a72960b/d32b942d-c57d-479d-b5e5-e771167ee7d8)

**Comment by sylwiabr** [comment] 2020-03-17 09:36
Moved back to backlog.

**Comment by wdanilo** [comment] 2020-03-18 13:04
Could you please provide me the info of `--version` and `--info` ?

**Comment by sylwiabr** [comment] 2020-03-18 16:22
info:
```
{
    "version": {
        "core": "2.0.0-alpha.0",
        "build": "b6ce9ef",
        "electron": "8.1.1",
        "chrome": "80.0.3987.141"
    },
    "creation": 1584548548457.66,
    "perf": {
        "cpu": {
            "percentCPUUsage": 0,
            "idleWakeupsPerSecond": 0
        }
    },
    "memory": {
        "heap": {
            "totalHeapSize": 10060,
            "totalHeapSizeExecutable": 512,
            "totalPhysicalSize": 8297,
            "totalAvailableSize": 4235708,
            "usedHeapSize": 7245,
            "heapSizeLimit": 4243456,
            "mallocedMemory": 8,
            "peakMallocedMemory": 1112,
            "doesZapGarbage": false
        },
        "blink": {
            "allocated": 0,
            "total": 0
        },
        "process": {
            "private": 23508,
            "shared": 8
        },
        "system": {
            "total": 16777216,
            "free": 637336
        }
    },
    "system": {
        "platform": "darwin",
        "arch": "x64",
        "version": "10.15.3"
    }
}

```

**Comment by sylwiabr** [comment] 2020-03-18 16:23
version:
```
core     : 2.0.0-alpha.0
build    : b6ce9ef
electron : 8.1.1
chrome   : 80.0.3987.141
```

**Comment by farmaazon** [comment] 2020-09-07 09:40
We use the standard window frame again, so perhaps it is fixed now @sylwiabr

**Comment by BinarySoftware** [comment] 2020-09-07 09:43
Yes, it is fixed, forgot to mention this issue in my PR.

**Closed** 2020-09-16 08:23 UTC
Labels: Category: GUI, Change: Non-Breaking, Priority: Low, Type: Bug
